### ISSUE TITLE
@container / @extend classes are not being resolved correctly

### ISSUE THREAD

**Issue by s1n7ax** [basro/stylance-rs#1]
classes used in `@media` quries are correcly being resolved.

![image](https://github.com/basro/stylance-rs/assets/18459807/f6f29537-9ecb-4ecf-81ff-c27a221e8a2a)

However, `@extend` & `@container` classes are not resolved and it's using the literal text in the original class name.

![image](https://github.com/basro/stylance-rs/assets/18459807/ba29a583-9109-4d11-a306-7b025b7448e2)

**Comment by s1n7ax** [comment]
@basro Hi, When pixel amount is used, container parsing works but when variable is used, parsing fails.

![image](https://github.com/basro/stylance-rs/assets/18459807/f9acc612-28f3-479c-bb0b-8c5b942063bd)


```scss
  @container (min-width: #{$screen-md}) {
    & {
      background-color: green;
      padding-left: 10rem;
      padding-right: 10rem;
    }
  }

```
