### ISSUE TITLE
Workspace Hash Issues?

### ISSUE THREAD

**Issue by ProfessorChill** [basro/stylance-rs#15]
I have a Cargo.toml in the root of the workspace that looks like so.
```toml
[package]
name = "project_name"

[lib]
crate-type = ["cdylib"]

[workspace]
resolver = "2"
members = ["app", "frontend", "server", "design-components"]

[package.metadata.stylance]
output_dir = "./style/"
folders = ["./design-components/src/", "./app/src/"]
extensions = [".module.scss"]
```
This compiles fine and it works fine with works perfectly, except the hash numbers don't match what's on the website so none of the styles work.

For example, on the live website via `cargo leptos watch` I get the hash `pet-list-container-3be9aa5` yet on the scss file in the style folder I get `pet-list-container-681f145`.
