### ISSUE TITLE
generate constants for class suffixes using parent '&' selector

### ISSUE THREAD

**Issue by a-irizi** [basro/stylance-rs#6]
i'm using stylance 0.5.1 with nightly feature enabled.

i noticed that for a scss file that contains defines some nested class like the following:
``` scss
.accordion {
  max-width: 600px;
  margin: 4rem auto;
  width: 90%;
  font-family: "Raleway", sans-serif;
  background: #f4f4f4;

  &__copy {
    display: none;
    padding: 1rem 1.5rem 2rem 1.5rem;
    color: gray;
    line-height: 1.6;
    font-size: 14px;
    font-weight: 500;

    &--open {
      display: block;
    }
  }
}
```

stylance will only generate a constant for the class `accordion` but not for the classes `accordion__copy` or `accordion__copy--open`.

is there a way to generate constants for those classes too, if not than i will have to just use css because nesting is the primary reason i use scss.
