### ISSUE TITLE
Q: source maps aren't quite working correctly

### ISSUE THREAD

**Issue by yatesco** [basro/stylance-rs#8]
**EDIT** - I've realised that this generates SCSS not CSS, so I've updated accordingly but still no luck :-(

I've created a demo https://github.com/yatesco/leptos-and-stylance-rs-hello-world. When I run `trunk serve` (which calls Stylance in the hook) then it generates one SCSS file per "module.scss" including the "_all.scss". If I include this as a SCSS resource in my "index.html": https://github.com/yatesco/leptos-and-stylance-rs-hello-world/blob/a1197c9e69dc2d7f4ec51fed9c44be49e690aad1/index.html#L5

then I can see that it (trunk?) does indeed generate a source map embedded into the (on the fly) generated CSS:
```css
.style-bb66a2d {
    background-color: lightblue;
}

.style-67eb31e {
    background-color: yellow;
}

/*# sourceMappingURL=data:application/json;charset=utf-8,%7B%22version%22:3,%22sourceRoot%22:%22%22,%22sources%22:%5B%22../../styles/stylance/app.module-bb66a2d.scss%22,%22../../styles/stylance/count.module-67eb31e.scss%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAAA;EACI;;;ACDJ;EACI%22,%22file%22:%22_index.css%22%7D */

```

However, if I inspect the element and then following the custom generated rules:

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/d9fde2fa-99c4-4e1d-a4c3-cf1491123145">

then following that link shows me some weird HTML:

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/152e6720-b1b3-4467-a80c-15385ad29b07">

Am I doing something wrong? Are source maps expected to work?

Thanks1
